name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - "**.ts"
      - "**.json"
      - ".github/workflows/test.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build
      # Currently we don't want to commit dist folder
      - uses: ./
        id: "check-success"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "success.yml"
      - uses: ./
        id: "check-failed"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "failed.yml"
      - name: Validate Result (If Statement)
        if: ${{ steps.check-success.outputs.conclusion == 'success' && steps.check-failed.outputs.conclusion == 'failure'}}
        run: exit 0
      - name: Validate Result (Shell)
        run: |
          if [ '${{ steps.check-success.outputs.conclusion }}' == 'success' -a '${{ steps.check-failed.outputs.conclusion }}' == 'failure' ]; then
            exit 0
          else
            exit 1
          fi

